kind: pipeline
name: default

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event: [tags]

  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - make ci
    depends_on: [clone]
    when:
      event: [pull_request]

  - name: validate commits
    image: commitsar/commitsar:0.7.0
    depends_on: [clone]
    when:
      event: [pull_request]

  - name: relase notes
    image: commitsar/release-notary:0.3.0
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GITHUB_REPOSITORY: $$DRONE_REPO
    when:
      event: tag
    depends_on: [fetch]

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag
    depends_on: [fetch]

volumes:
  - name: deps
    temp: {}
